### ISSUE TITLE
Some model files might be missing...

### ISSUE THREAD

**Issue by xxl95** [monologg/R-BERT#5]
06/21/2020 10:13:15 - INFO - transformers.modeling_utils -   loading weights file ./model\pytorch_model.bin
Traceback (most recent call last):
  File "D:\WorkSpace\Pythonspace\R-BERT-master\trainer.py", line 200, in load_model
    self.model = self.model_class.from_pretrained(self.args.model_dir)
  File "D:\Programming\Anaconda3\lib\site-packages\transformers\modeling_utils.py", line 512, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() missing 1 required positional argument: 'args'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/WorkSpace/Pythonspace/R-BERT-master/main.py", line 63, in <module>
    main(args)
  File "D:/WorkSpace/Pythonspace/R-BERT-master/main.py", line 21, in main
    trainer.load_model()
  File "D:\WorkSpace\Pythonspace\R-BERT-master\trainer.py", line 204, in load_model
    raise Exception("Some model files might be missing...")
Exception: Some model files might be missing...

**Comment by eric-0x72** [comment]
you might want to output the real error? 
```python
except Exception as e:
    print("error: ", e)
    raise Exception("Some model files might be missing...")
```

**Comment by xxl95** [comment]
Thanks a lot!!

**Comment by chenhaishun** [comment]
@xxl95 I had the same problem,may I ask how you solved it?

**Comment by monologg** [comment]
@xxl95  @chenhaishun 
There were some bugs when I refactored the code.
I've fixed the issue. Please pull the new commit:)

**Comment by monologg** [comment]
Closing, feel free to reopen:)
